<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>
    <div class="row">
        <h1>Kaffie</h1>

         </head>
       <form method="POST" action="/add">
    <body>
 
      <div class="row">
        <div class="input-field col s2 offset-s4">
          <i class="material-icons prefix">playlist_add</i>
          <input type="text" id="autocomplete-input" class="autocomplete" name="title">
          <label for="autocomplete-input">Name</label>
        </div>
        <div class="input-field col s1">
          <i class="material-icons prefix">monetization_on</i>
          <input type="text" id="autocomplete-input" class="datepicker" name="date">
          <label for="autocomplete-input">Price</label>
        </div>
        <div class="input-field col s1">
          <i class="material-icons prefix">poll</i>
          <input type="text" id="autocomplete-input" class="timepicker" name="time">
          <label for="autocomplete-input">Quantity</label>
        </div>
      </div>



      <div class="row">
        <div class="input-field col s4 offset-s4">
          <i class="material-icons prefix">info</i>
          <input type="text" id="autocomplete-input" class="autocomplete" name="description">
          <label for="autocomplete-input">Description</label>
        </div>
      </div>

<div class="row">
        <button class="btn waves-effect waves-light" type="submit" name="action">Add product<i class="material-icons right">send</i></button>
        <a href="/stock" class="btn waves-effect waves-light">Cancel<i class="material-icons right">send</i></a>
</div>

</form>
    </body>
</html>