<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <script src="/js/app.js"></script>
    </head>       
    <body>
    <?php
        use \App\Models\Customer;
        use \App\Listcreator\ListCreator;

        $customers = Customer::all();

        $fileRoute = "/customers/";

        $listIcon = "assignment_ind";

        $customerIdArray = [];
        $customerList = [];

        $title = "Customers";

        foreach ($customers as $customer)
        {
            $id = $customer->id;
            array_push($customerIdArray, $id);

            $firstname = $customer->firstname;
            $lastname = $customer->lastname;

            $listInput = $firstname . " " . $lastname;
            array_push($customerList, $listInput);
        }
        echo $customerList = new ListCreator($fileRoute, $listIcon, $customerIdArray, $title, $customerList);
        ?>
        <br>
        <div class="row">
            <a  href="/overview" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
            <a  href="/addCustomers" class="waves-effect waves-light btn-large"><i class="material-icons right">add</i>Add customer</a>
        </div>
    </body>
</html>