<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link rel='shortcut icon' type='image/PNG' href='images/favicon.PNG' />
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="/js/app.js"></script>

        <style>
            body {
                margin: 5px 0 0 0;
                padding: 0 100px 0 100px;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #a7a7a7;
                font-size: 18px;
                background-color: white;
            }

            h1 {
                color: #26A69A;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 85px;
                font-weight: 200;
                margin-bottom: 150;
            } 

        </style>
    </head>
       
    <body>

    </body>
</html>