<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kaffie</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="row">
    <h1>Kaffie</h1>
        <form action="POST" action="/edit"> 
        
            <div class="row">
                    <a  href="/stock" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
            </div>
        </form>
    </div>
</body>
</html>