<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kaffie</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="row">
    <h1>Kaffie</h1>

<form action="/profile" method="put">

    <div class="row" style="margin-left: 34%">
    <div class="input-field col s6">
                    <i class="material-icons prefix">lock</i>
                    <input id="old_assword" required="required" name="password" type="password" class="validate">
                    <label for="password">Old password</label>
                    </div>
    </div>
    
    <div class="row" style="margin-left: 34%">
                    <div class="input-field col s3">
                    <i class="material-icons prefix">lock</i>
                    <input id="password" required="required" name="password" type="password" class="validate">
                    <label for="password">New password</label>
                    </div>
                    <div class="input-field col s3">
                    <i class="material-icons prefix">lock</i>
                    <input id="confirmpassword" required="required" name="confirmpassword" type="password" class="validate">
                    <label for="confirmpassword">Confirm new assword</label>
                    </div>
                    </div>

<div class="row">
        <a  href="/profile" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
        <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Save Password<i class="material-icons right">save</i></button>
    </div>
    </form>
</body>
</html>