<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <?php
    if (isset($_SESSION['authorized']) && $_SESSION['authorized'] === TRUE) {
        // Alright, let's show all the hidden functionality!
        if (isset($firstname))
        {
            echo "<h4>Welcome $firstname!</h4>";
        }
        else
        {
            echo "Welcome!";
        }
        
    } else {
        // User is not authorized!
        header('Location: login.php');
        exit();
    }
   
    ?>
    <br>
    <br>
    <div class="row">
    <a  href="/login" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
    <a  href="/profile" class="waves-effect waves-light btn-large"><i class="material-icons right">account_circle</i>My profile</a>
    <a  href="/customers" class="waves-effect waves-light btn-large"><i class="material-icons right">group</i>Customers</a>
    <a  href="/stock" class="waves-effect waves-light btn-large"><i class="material-icons right">format_list_bulleted</i>Stock</a>
    </div>
</body>
</html>