<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kaffie</title>
    <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    HELLO <?= $email ?>

    <a  href="/" class="waves-effect waves-light btn-large"><i class="material-icons right">exit_to_app</i>Back</a>
    <a  href="/" class="waves-effect waves-light btn-large"><i class="material-icons right">submit</i>Stock</a>
</body>
</html>