<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <script src="/js/app.js"></script>
    </head>       
    <body>
        <div class="row">
        <h1>Kaffie</h1>
        <?php
        use \App\Models\User;

            $id= 1;
            $user = User::find($id);
                echo $user->firstname;
                echo $user->lastname;
                echo $user->email;
                echo $user->address;
                echo $user->zip;
                echo $user->city;
?>
            <br>
            <br>
            <a  href="/overview" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
            <a  href="/logout" class="waves-effect waves-light btn-large"><i class="material-icons right">exit_to_app</i>Log out</a>
            <a  href="/editPassword" class="waves-effect waves-light btn-large"><i class="material-icons right">edit</i>Edit Password</a>
        </div>
    </body>
</html>