<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <script src="/js/app.js"></script>
    </head>       
    <body>
        <div class="row">
        <h1 style="margin-top:0">Kaffie</h1>
        <?php
        use \App\Models\User;

            $id= 1;
            $user = User::find($id);
                $firstname = $user->firstname;
                $lastname = $user->lastname;
                $email = $user->email;
                $address = $user->address;
                $zip = $user->zip;
                $city = $user->city;
?>
        <div class="form"> 
            <div class="row">
                <form class="col s6 offset-s3" method="put" action="/profile">
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="first_name" required="required" name="first_name" type="text" class="validate" value="<?php echo $firstname;?>">
                    <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="last_name" required="required" name="last_name" type="text"  class="validate" value="<?php echo $lastname;?>">
                    <label for="last_name">Last Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                    <i class="material-icons prefix">email</i>
                    <input id="email" name="email" required="required" type="email" class="validate" value="<?php echo $email;?>">
                    <label for="email">E-mail</label>
                    <span class="helper-text" data-error="Invalid e-mail!" data-success="Valid e-mail."></span>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">markunread_mailbox</i>
                    <input id="address" name="address" required="required" type="text" class="validate" value="<?php echo $address;?>">
                    <label for="email">Address</label>
                    </div>
                    <div class="input-field col s3">
                    <i class="material-icons prefix">markunread_mailbox</i>
                    <input id="zip" name="zip" required="required" type="text" class="validate" value="zip">
                    <label for="zip">Zip</label>
                    </div>
                    <div class="input-field col s3">
                    <i class="material-icons prefix">location_city</i>
                    <input id="city" name="city" required="required" type="text" class="validate" value="city">
                    <label for="city">City</label>
                    </div>
                </div>
                </form>
            </div>
        </div>
            <a  href="/overview" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
            <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Save<i class="material-icons right">save</i></button>
            <a  href="/editPassword" class="waves-effect waves-light btn-large"><i class="material-icons right">edit</i>Edit Password</a>
            <a  href="/logout" class="waves-effect waves-light btn-large"><i class="material-icons right">exit_to_app</i>Log out</a>

        </div>
    </body>
</html>