<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    </head>
    <body>
        <h1>Kaffie</h1>

    <form class="col s6 offset-s3">
        <div class="form">
            <div class="row">       
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="first_name" type="text" class="validate">
                    <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="last_name" type="text" class="validate">
                    <label for="last_name">Last Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">lock</i>
                    <input id="password" type="password" class="validate">
                    <label for="password">Password</label>
                    </div>
                    <div class="input-field col s6">
                    <i class="material-icons prefix">lock</i>
                    <input id="confirmpassword" type="password" class="validate">
                    <label for="confirmpassword">Confirm Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                    <i class="material-icons prefix">email</i>
                    <input id="email" type="email" class="validate">
                    <label for="email">E-mail</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">markunread_mailbox</i>
                    <input id="address" type="text" class="validate">
                    <label for="email">Address</label>
                    </div>
                    <div class="input-field col s3">
                    <i class="material-icons prefix">markunread_mailbox</i>
                    <input id="zip" type="text" class="validate">
                    <label for="zip">Zip</label>
                    </div>
                    <div class="input-field col s3">
                    <i class="material-icons prefix">location_city</i>
                    <input id="city" type="text" class="validate">
                    <label for="city">City</label>
                    </div>
                </div> 
            </div>
        </div>
        <a  href="/" class="waves-effect waves-light btn-large"><i class="material-icons right">exit_to_app</i>Back</a>
        <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Submit<i class="material-icons right">send</i></button>
    </form>
    </body>
</html>