<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <script src="/js/app.js"></script>
    </head>       
        <body>
        
        <?php
        use \App\Models\Product;
        use \App\Listcreator\ListCreator;

        $products = Product::all();

        $fileRoute = "/stock/";

        $productIdArray = [];
        $productList = [];

        $title = "Products in stock";

        foreach ($products as $product)
        {
            $id = $product->id;
            array_push($productIdArray, $id);

            $name = $product->name;
            $quantity = $product->quantity;

            $listInput = $name . ", amount in stock: " . $quantity;
            array_push($productList, $listInput);
        }
        echo $productList = new ListCreator($fileRoute, $productIdArray, $title, $productList);
        ?>

        <br>
        <div class="row">
            <a  href="/overview" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
            <a href="/add" class="btn waves-effect waves-light btn-large"><i class="material-icons right">add</i>Add product</a>
        </div>
    </body>
</html>

