<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8"/>
        <title>Kaffie</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="icon" href="/favicon/kaffie_logo.png" type="image/png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
    </head>
       
        <body>

        <?php 

        use \App\Models\Product;

        $products = Product::all();
        
        foreach($products as $product){
            $productId = $product->id;
            $productName = $product->name;
            $productQuantity = $product->quantity;

            echo $productId . ". " . $productName;
        }

    ?>
    
        <div class="row">
        <a href="/add" class="btn waves-effect waves-light btn-large">Add product<i class="material-icons right">send</i></a>
        </div>
    </body>
</html>

